const testQuestions = [
  {
    id: 1,
    test: "ielts",
    question: "Which of the following is part of the IELTS test format?",
    options: ["Reading", "Listening", "Speaking", "All of the above"],
    correctAnswer: "All of the above",
  },
  {
    id: 2,
    test: "ielts",
    question: "How long is the IELTS speaking test?",
    options: ["5-10 minutes", "11-14 minutes", "20 minutes", "30 minutes"],
    correctAnswer: "11-14 minutes",
  },
  {
    id: 3,
    test: "ielts",
    question: "How many sections are there in the IELTS Listening test?",
    options: ["2", "3", "4", "5"],
    correctAnswer: "4",
  },
  {
    id: 4,
    test: "ielts",
    question: "Which skill is tested in Task 1 of the IELTS Academic Writing section?",
    options: ["Essay writing", "Letter writing", "Report writing", "Story writing"],
    correctAnswer: "Report writing",
  },
  {
    id: 5,
    test: "ielts",
    question: "What is the highest band score in IELTS?",
    options: ["8", "9", "10", "12"],
    correctAnswer: "9",
  },
  {
    id: 6,
    test: "ielts",
    question: "Which of the following is a common topic in the IELTS Speaking section?",
    options: ["Politics", "Personal experiences", "Programming", "Physics"],
    correctAnswer: "Personal experiences",
  },
  {
    id: 7,
    test: "ielts",
    question: "What is the time duration for the IELTS Reading test?",
    options: ["30 minutes", "40 minutes", "60 minutes", "90 minutes"],
    correctAnswer: "60 minutes",
  },
  {
    id: 8,
    test: "ielts",
    question: "Which IELTS version is intended for students aiming for academic studies?",
    options: ["General Training", "Academic", "Professional", "Basic"],
    correctAnswer: "Academic",
  },
  {
    id: 9,
    test: "ielts",
    question: "Which section comes first in the IELTS test?",
    options: ["Speaking", "Listening", "Reading", "Writing"],
    correctAnswer: "Listening",
  },
  {
    id: 10,
    test: "ielts",
    question: "What is the usual number of questions in the Listening test?",
    options: ["20", "30", "40", "50"],
    correctAnswer: "40",
  },
  {
    id: 11,
    test: "ielts",
    question: "How many writing tasks are there in the IELTS test?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
  },
  {
    id: 12,
    test: "ielts",
    question: "How is the IELTS test scored?",
    options: ["Percentage", "Points", "Band scale", "Stars"],
    correctAnswer: "Band scale",
  },
  {
    id: 13,
    test: "ielts",
    question: "Which of the following is a feature of IELTS Academic Reading?",
    options: ["Emails", "Graphs", "Scientific articles", "Comics"],
    correctAnswer: "Scientific articles",
  },
  {
    id: 14,
    test: "ielts",
    question: "What is the format of the IELTS Speaking test?",
    options: ["Face to face", "Group discussion", "Online quiz", "Written exam"],
    correctAnswer: "Face to face",
  },
  {
    id: 15,
    test: "ielts",
    question: "How often can you take the IELTS test?",
    options: ["Only once", "Every 6 months", "Once a year", "As many times as needed"],
    correctAnswer: "As many times as needed",
  },
  {
    id: 16,
    test: "ielts",
    question: "What is tested in Task 2 of the IELTS Writing test?",
    options: ["Letter", "Essay", "Chart", "Summary"],
    correctAnswer: "Essay",
  },
  {
    id: 17,
    test: "ielts",
    question: "Which of the following is a type of question in IELTS Reading?",
    options: ["Multiple choice", "True/False/Not Given", "Matching headings", "All of the above"],
    correctAnswer: "All of the above",
  },
  {
    id: 18,
    test: "ielts",
    question: "How long is the IELTS Listening test?",
    options: ["30 minutes", "45 minutes", "60 minutes", "75 minutes"],
    correctAnswer: "30 minutes",
  },
  {
    id: 19,
    test: "ielts",
    question: "Can the IELTS Speaking test be on a different day than the other parts?",
    options: ["No", "Yes", "Only for Academic", "Only for General"],
    correctAnswer: "Yes",
  },
  {
    id: 20,
    test: "ielts",
    question: "What is the minimum band score required by most universities?",
    options: ["4.0", "5.5", "6.5", "8.0"],
    correctAnswer: "6.5",
  },
  
    // SAT Questions
  {
    id: 21,
    test: "sat",
    question: "What is the total score range for the SAT?",
    options: ["200–1600", "400–1600", "0–2400", "800–2400"],
    correctAnswer: "400–1600",
  },
  {
    id: 22,
    test: "sat",
    question: "Which two main sections make up the SAT score?",
    options: ["Math and Writing", "Reading and Writing", "Math and Evidence-Based Reading and Writing", "Science and Math"],
    correctAnswer: "Math and Evidence-Based Reading and Writing",
  },
  {
    id: 23,
    test: "sat",
    question: "How long is the SAT without the essay?",
    options: ["2 hours", "3 hours", "3 hours 30 minutes", "4 hours"],
    correctAnswer: "3 hours",
  },
  {
    id: 24,
    test: "sat",
    question: "How many Math sections are there in the SAT?",
    options: ["1", "2", "3", "4"],
    correctAnswer: "2",
  },
  {
    id: 25,
    test: "sat",
    question: "What type of math is NOT typically included in the SAT?",
    options: ["Algebra", "Geometry", "Calculus", "Statistics"],
    correctAnswer: "Calculus",
  },
  {
    id: 26,
    test: "sat",
    question: "Which tool is allowed during part of the Math section?",
    options: ["Calculator", "Ruler", "Compass", "Graphing paper"],
    correctAnswer: "Calculator",
  },
  {
    id: 27,
    test: "sat",
    question: "How many passages are there in the Reading section?",
    options: ["2", "3", "4", "5"],
    correctAnswer: "5",
  },
  {
    id: 28,
    test: "sat",
    question: "What is the time limit for the SAT Reading section?",
    options: ["50 minutes", "60 minutes", "65 minutes", "70 minutes"],
    correctAnswer: "65 minutes",
  },
  {
    id: 29,
    test: "sat",
    question: "What is one of the key skills tested in the Writing section?",
    options: ["Vocabulary memorization", "Sentence structure", "Drawing", "Poetry analysis"],
    correctAnswer: "Sentence structure",
  },
  {
    id: 30,
    test: "sat",
    question: "Which organization administers the SAT?",
    options: ["ETS", "ACT, Inc.", "College Board", "Cambridge"],
    correctAnswer: "College Board",
  },
  {
    id: 31,
    test: "sat",
    question: "Is the SAT currently available in a digital format?",
    options: ["Yes", "No", "Only in the US", "Only for international students"],
    correctAnswer: "Yes",
  },
  {
    id: 32,
    test: "sat",
    question: "What kind of questions are included in the Math section?",
    options: ["Multiple choice", "Grid-in", "Both", "Only essays"],
    correctAnswer: "Both",
  },
  {
    id: 33,
    test: "sat",
    question: "What does EBRW stand for in SAT scoring?",
    options: ["English-Based Reading and Writing", "Evidence-Based Reading and Writing", "Efficient-Based Reading and Writing", "Exam-Based Reading and Writing"],
    correctAnswer: "Evidence-Based Reading and Writing",
  },
  {
    id: 34,
    test: "sat",
    question: "What is the max score for each section of the SAT?",
    options: ["400", "600", "800", "1000"],
    correctAnswer: "800",
  },
  {
    id: 35,
    test: "sat",
    question: "What is a good SAT score out of 1600?",
    options: ["900", "1000", "1200+", "800"],
    correctAnswer: "1200+",
  },
  {
    id: 36,
    test: "sat",
    question: "How is the SAT Writing section structured?",
    options: ["Grammar and punctuation questions", "Reading comprehension", "Short essay", "Long essay"],
    correctAnswer: "Grammar and punctuation questions",
  },
  {
    id: 37,
    test: "sat",
    question: "What is the SAT Essay section now optional for?",
    options: ["Math students", "Everyone", "Reading students", "Writing students"],
    correctAnswer: "Everyone",
  },
  {
    id: 38,
    test: "sat",
    question: "Which of the following does the SAT NOT test?",
    options: ["Math", "Science", "Writing", "Reading"],
    correctAnswer: "Science",
  },
  {
    id: 39,
    test: "sat",
    question: "How many sections does the SAT have?",
    options: ["3", "4", "5", "6"],
    correctAnswer: "4",
  },
  {
    id: 40,
    test: "sat",
    question: "What is a good strategy for answering the Reading questions?",
    options: ["Skim through passages quickly", "Read each passage fully", "Guess answers", "Ignore the vocabulary questions"],
    correctAnswer: "Read each passage fully",
  },
  
    // PTE - Set A
    {
      id: 9,
      set: "set-a",
      test: "pte",
      question: "How is the PTE exam delivered?",
      options: ["Paper-based", "Computer-based", "Oral exam", "Written exam"],
      correctAnswer: "Computer-based",
    },
    {
      id: 10,
      set: "set-a",
      test: "pte",
      question: "What is the maximum score for each section in PTE?",
      options: ["50", "100", "90", "80"],
      correctAnswer: "90",
    },
  
    // PTE - Set B
    {
      id: 41,
      test: "pte",
      question: "What does PTE stand for?",
      options: ["Personal Test of English", "Professional Test of English", "Pearson Test of English", "Public Test of English"],
      correctAnswer: "Pearson Test of English",
    },
    {
      id: 42,
      test: "pte",
      question: "Which section of the PTE is designed to test speaking skills?",
      options: ["Reading", "Speaking and Writing", "Listening", "Writing"],
      correctAnswer: "Speaking and Writing",
    },
    {
      id: 43,
      test: "pte",
      question: "How many sections are in the PTE Academic test?",
      options: ["2", "3", "4", "5"],
      correctAnswer: "3",
    },
    {
      id: 44,
      test: "pte",
      question: "What is the maximum score in the PTE Academic exam?",
      options: ["90", "100", "120", "150"],
      correctAnswer: "90",
    },
    {
      id: 45,
      test: "pte",
      question: "What is the total time duration of the PTE Academic test?",
      options: ["2 hours", "3 hours", "3 hours 30 minutes", "4 hours"],
      correctAnswer: "3 hours",
    },
    {
      id: 46,
      test: "pte",
      question: "What is the scoring range for each section of the PTE?",
      options: ["10–90", "20–80", "30–100", "50–150"],
      correctAnswer: "10–90",
    },
    {
      id: 47,
      test: "pte",
      question: "Which of the following is NOT a section in the PTE Academic test?",
      options: ["Speaking and Writing", "Reading", "Listening", "Math"],
      correctAnswer: "Math",
    },
    {
      id: 48,
      test: "pte",
      question: "What type of questions are included in the Reading section of PTE?",
      options: ["Multiple-choice", "True/False/Not Given", "Fill in the blanks", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 49,
      test: "pte",
      question: "What is the minimum age requirement for taking the PTE Academic test?",
      options: ["16 years", "18 years", "21 years", "No minimum age"],
      correctAnswer: "16 years",
    },
    {
      id: 50,
      test: "pte",
      question: "Which of the following skills does the PTE Speaking section NOT assess?",
      options: ["Pronunciation", "Fluency", "Grammar", "Vocabulary"],
      correctAnswer: "Grammar",
    },
    {
      id: 51,
      test: "pte",
      question: "What kind of task is included in the PTE Speaking and Writing section?",
      options: ["Reading aloud", "Summarizing spoken text", "Essay writing", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 52,
      test: "pte",
      question: "What is the maximum score for the Speaking and Writing section?",
      options: ["15", "30", "45", "90"],
      correctAnswer: "90",
    },
    {
      id: 53,
      test: "pte",
      question: "How are PTE Academic test results typically available?",
      options: ["Within 1 week", "Within 2 weeks", "Within 3 days", "Within 24 hours"],
      correctAnswer: "Within 3 days",
    },
    {
      id: 54,
      test: "pte",
      question: "What does the Listening section of PTE test?",
      options: ["Ability to comprehend spoken English", "Ability to write down what you hear", "Ability to answer questions based on audio", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 55,
      test: "pte",
      question: "What is the time duration for the PTE Speaking section?",
      options: ["5 minutes", "10 minutes", "15 minutes", "20 minutes"],
      correctAnswer: "10 minutes",
    },
    {
      id: 56,
      test: "pte",
      question: "Which part of the PTE Academic test assesses listening and writing together?",
      options: ["Reading", "Speaking", "Listening", "Writing"],
      correctAnswer: "Writing",
    },
    {
      id: 57,
      test: "pte",
      question: "Which of the following is part of the Listening section?",
      options: ["Summarize spoken text", "Repeat sentences", "Multiple-choice questions", "All of the above"],
      correctAnswer: "All of the above",
    },
    {
      id: 58,
      test: "pte",
      question: "Which of the following PTE sections contains multiple-choice questions with multiple answers?",
      options: ["Reading", "Writing", "Speaking", "Listening"],
      correctAnswer: "Listening",
    },
    {
      id: 59,
      test: "pte",
      question: "Which of the following is not a speaking task in the PTE?",
      options: ["Repeat sentence", "Describe image", "Write essay", "Read aloud"],
      correctAnswer: "Write essay",
    },
    {
      id: 60,
      test: "pte",
      question: "What is the time duration for the PTE Reading section?",
      options: ["30 minutes", "35 minutes", "40 minutes", "45 minutes"],
      correctAnswer: "35 minutes",
    },
  
    // TOEFL - Set A
    {
      id: 61,
      test: "toefl",
      question: "What does TOEFL stand for?",
      options: ["Test of English as a Foreign Language", "Test of English for Foreign Learners", "Test of Official English for Learners", "Teaching of English as a Foreign Language"],
      correctAnswer: "Test of English as a Foreign Language",
    },
    {
      id: 62,
      test: "toefl",
      question: "What are the four sections in the TOEFL exam?",
      options: ["Reading, Listening, Speaking, Writing", "Reading, Writing, Listening, Grammar", "Listening, Speaking, Vocabulary, Writing", "Grammar, Vocabulary, Speaking, Listening"],
      correctAnswer: "Reading, Listening, Speaking, Writing",
    },
    {
      id: 63,
      test: "toefl",
      question: "What is the time duration for the TOEFL exam?",
      options: ["2 hours", "3 hours", "4 hours", "5 hours"],
      correctAnswer: "3 hours",
    },
    {
      id: 64,
      test: "toefl",
      question: "What is the maximum score in TOEFL?",
      options: ["100", "110", "120", "150"],
      correctAnswer: "120",
    },
    {
      id: 65,
      test: "toefl",
      question: "How long are TOEFL scores valid?",
      options: ["1 year", "2 years", "5 years", "10 years"],
      correctAnswer: "2 years",
    },
    {
      id: 66,
      test: "toefl",
      question: "Which section in TOEFL measures listening comprehension?",
      options: ["Reading", "Writing", "Speaking", "Listening"],
      correctAnswer: "Listening",
    },
    {
      id: 67,
      test: "toefl",
      question: "Which of the following is NOT included in the TOEFL exam?",
      options: ["Writing an essay", "Reading comprehension", "Speaking with a native speaker", "Listening to recorded conversations"],
      correctAnswer: "Speaking with a native speaker",
    },
    {
      id: 68,
      test: "toefl",
      question: "In which section of TOEFL are you required to speak about a given topic?",
      options: ["Speaking", "Writing", "Listening", "Reading"],
      correctAnswer: "Speaking",
    },
    {
      id: 69,
      test: "toefl",
      question: "What is the primary purpose of the TOEFL exam?",
      options: ["To measure the English language proficiency of non-native speakers", "To test knowledge of English grammar", "To evaluate vocabulary comprehension", "To assess listening skills only"],
      correctAnswer: "To measure the English language proficiency of non-native speakers",
    },
    {
      id: 70,
      test: "toefl",
      question: "How is the TOEFL Speaking section scored?",
      options: ["On a scale of 0–30", "On a scale of 0–15", "On a scale of 0–10", "On a scale of 0–50"],
      correctAnswer: "On a scale of 0–30",
    },
    {
      id: 71,
      test: "toefl",
      question: "Which of the following is a listening task in TOEFL?",
      options: ["Summarizing spoken text", "Writing a response to a question", "Reading comprehension", "Listening to a lecture and answering questions"],
      correctAnswer: "Listening to a lecture and answering questions",
    },
    {
      id: 72,
      test: "toefl",
      question: "How long is the TOEFL Speaking section?",
      options: ["10 minutes", "15 minutes", "20 minutes", "30 minutes"],
      correctAnswer: "20 minutes",
    },
    {
      id: 73,
      test: "toefl",
      question: "In the TOEFL Reading section, how long do you have to answer questions for each passage?",
      options: ["15 minutes", "20 minutes", "25 minutes", "30 minutes"],
      correctAnswer: "20 minutes",
    },
    {
      id: 74,
      test: "toefl",
      question: "How many tasks are there in the TOEFL Speaking section?",
      options: ["3", "4", "5", "6"],
      correctAnswer: "6",
    },
    {
      id: 75,
      test: "toefl",
      question: "What does the TOEFL Writing section assess?",
      options: ["Ability to write essays", "Ability to understand spoken English", "Ability to summarize spoken text", "Ability to respond to questions verbally"],
      correctAnswer: "Ability to write essays",
    },
    {
      id: 76,
      test: "toefl",
      question: "What is the primary focus of the TOEFL Reading section?",
      options: ["Identifying key details in a passage", "Listening comprehension", "Expressing opinions about a topic", "Recognizing grammar mistakes in sentences"],
      correctAnswer: "Identifying key details in a passage",
    },
    {
      id: 77,
      test: "toefl",
      question: "Which of the following is NOT a task in the TOEFL Writing section?",
      options: ["Essay writing", "Summarizing a passage", "Answering multiple-choice questions", "Writing a response to a question"],
      correctAnswer: "Answering multiple-choice questions",
    },
    {
      id: 78,
      test: "toefl",
      question: "How many questions are there in the TOEFL Listening section?",
      options: ["10–20", "20–30", "30–40", "40–50"],
      correctAnswer: "28–39",
    },
    {
      id: 79,
      test: "toefl",
      question: "Which section of TOEFL involves writing an essay on a given topic?",
      options: ["Speaking", "Listening", "Writing", "Reading"],
      correctAnswer: "Writing",
    },
    {
      id: 80,
      test: "toefl",
      question: "What is the maximum score you can achieve in TOEFL Speaking?",
      options: ["10", "15", "20", "30"],
      correctAnswer: "30",
    },
  
    // GRE - Set A
    {
      id: 81,
      test: "gre",
      question: "What does GRE stand for?",
      options: ["Graduate Record Examination", "General Record Examination", "Graduate Reasoning Examination", "General Reasoning Examination"],
      correctAnswer: "Graduate Record Examination",
    },
    {
      id: 82,
      test: "gre",
      question: "What is the maximum score on the GRE?",
      options: ["150", "160", "170", "180"],
      correctAnswer: "340",
    },
    {
      id: 83,
      test: "gre",
      question: "What sections are included in the GRE?",
      options: ["Verbal Reasoning, Quantitative Reasoning, Analytical Writing", "Verbal Reasoning, Analytical Writing, Logical Reasoning", "Math, Reading, Analytical Writing", "Math, Verbal, Essay"],
      correctAnswer: "Verbal Reasoning, Quantitative Reasoning, Analytical Writing",
    },
    {
      id: 84,
      test: "gre",
      question: "How many questions are there in the GRE Verbal Reasoning section?",
      options: ["20", "30", "40", "50"],
      correctAnswer: "40",
    },
    {
      id: 85,
      test: "gre",
      question: "What is the time limit for the GRE Analytical Writing section?",
      options: ["30 minutes", "40 minutes", "60 minutes", "75 minutes"],
      correctAnswer: "60 minutes",
    },
    {
      id: 86,
      test: "gre",
      question: "Which of the following is NOT a topic covered in the GRE Verbal Reasoning section?",
      options: ["Reading Comprehension", "Text Completion", "Sentence Equivalence", "Mathematical Reasoning"],
      correctAnswer: "Mathematical Reasoning",
    },
    {
      id: 87,
      test: "gre",
      question: "How long is the GRE Quantitative Reasoning section?",
      options: ["35 minutes", "40 minutes", "45 minutes", "50 minutes"],
      correctAnswer: "40 minutes",
    },
    {
      id: 88,
      test: "gre",
      question: "What is the scoring range for the GRE Verbal Reasoning section?",
      options: ["130–170", "120–160", "150–200", "100–150"],
      correctAnswer: "130–170",
    },
    {
      id: 89,
      test: "gre",
      question: "Which section of the GRE has an issue essay?",
      options: ["Verbal Reasoning", "Quantitative Reasoning", "Analytical Writing", "Reading Comprehension"],
      correctAnswer: "Analytical Writing",
    },
    {
      id: 90,
      test: "gre",
      question: "What is the time limit for the GRE Quantitative Reasoning section?",
      options: ["30 minutes", "35 minutes", "40 minutes", "45 minutes"],
      correctAnswer: "40 minutes",
    },
    {
      id: 91,
      test: "gre",
      question: "How many total questions are there in the GRE Quantitative Reasoning section?",
      options: ["30", "40", "45", "50"],
      correctAnswer: "40",
    },
    {
      id: 92,
      test: "gre",
      question: "Which of the following topics is NOT included in the GRE Quantitative Reasoning section?",
      options: ["Algebra", "Geometry", "Probability", "Vocabulary"],
      correctAnswer: "Vocabulary",
    },
    {
      id: 93,
      test: "gre",
      question: "Which section of the GRE includes sentence equivalence questions?",
      options: ["Quantitative Reasoning", "Verbal Reasoning", "Analytical Writing", "Reading Comprehension"],
      correctAnswer: "Verbal Reasoning",
    },
    {
      id: 94,
      test: "gre",
      question: "What is the time limit for the GRE Verbal Reasoning section?",
      options: ["30 minutes", "35 minutes", "40 minutes", "45 minutes"],
      correctAnswer: "40 minutes",
    },
    {
      id: 95,
      test: "gre",
      question: "How many total questions are there in the GRE Verbal Reasoning section?",
      options: ["20", "30", "35", "40"],
      correctAnswer: "40",
    },
    {
      id: 96,
      test: "gre",
      question: "Which of the following is an example of a GRE Analytical Writing task?",
      options: ["Compare and contrast two statements", "Write an essay on a given topic", "Solve a word problem", "Select the best answer from a list of options"],
      correctAnswer: "Write an essay on a given topic",
    },
    {
      id: 97,
      test: "gre",
      question: "What is the time limit for each essay in the GRE Analytical Writing section?",
      options: ["20 minutes", "30 minutes", "40 minutes", "45 minutes"],
      correctAnswer: "30 minutes",
    },
    {
      id: 98,
      test: "gre",
      question: "Which of the following types of questions are found in the GRE Quantitative Reasoning section?",
      options: ["Reading comprehension", "Sentence completion", "Problem solving and data interpretation", "Essay writing"],
      correctAnswer: "Problem solving and data interpretation",
    },
    {
      id: 99,
      test: "gre",
      question: "What is the maximum score for the GRE Analytical Writing section?",
      options: ["1", "4", "6", "8"],
      correctAnswer: "6",
    },
    {
      id: 100,
      test: "gre",
      question: "How many sections are there in the GRE?",
      options: ["3", "4", "5", "6"],
      correctAnswer: "3",
    },
  
    // GMAT - Set A
    {
      id: 101,
      test: "gmat",
      question: "What does GMAT stand for?",
      options: ["Graduate Management Admission Test", "General Management Admission Test", "Graduate Mathematical Admission Test", "General Mathematical Admission Test"],
      correctAnswer: "Graduate Management Admission Test",
    },
    {
      id: 102,
      test: "gmat",
      question: "What is the maximum score on the GMAT?",
      options: ["600", "700", "800", "1000"],
      correctAnswer: "800",
    },
    {
      id: 103,
      test: "gmat",
      question: "Which of the following is NOT a section in the GMAT?",
      options: ["Quantitative Reasoning", "Verbal Reasoning", "Logical Reasoning", "Integrated Reasoning"],
      correctAnswer: "Logical Reasoning",
    },
    {
      id: 104,
      test: "gmat",
      question: "How long is the GMAT exam?",
      options: ["2 hours", "3 hours", "3.5 hours", "4 hours"],
      correctAnswer: "3.5 hours",
    },
    {
      id: 105,
      test: "gmat",
      question: "What is the time limit for the GMAT Analytical Writing section?",
      options: ["20 minutes", "30 minutes", "40 minutes", "45 minutes"],
      correctAnswer: "30 minutes",
    },
    {
      id: 106,
      test: "gmat",
      question: "How many questions are there in the GMAT Quantitative Reasoning section?",
      options: ["20", "30", "37", "50"],
      correctAnswer: "31",
    },
    {
      id: 107,
      test: "gmat",
      question: "Which of the following is NOT tested in the GMAT Quantitative Reasoning section?",
      options: ["Problem Solving", "Data Sufficiency", "Reading Comprehension", "Arithmetic"],
      correctAnswer: "Reading Comprehension",
    },
    {
      id: 108,
      test: "gmat",
      question: "What is the maximum score for the GMAT Analytical Writing Assessment?",
      options: ["2", "4", "6", "8"],
      correctAnswer: "6",
    },
    {
      id: 109,
      test: "gmat",
      question: "How many questions are there in the GMAT Verbal Reasoning section?",
      options: ["25", "30", "36", "41"],
      correctAnswer: "36",
    },
    {
      id: 110,
      test: "gmat",
      question: "What is the scoring range for the GMAT Quantitative Reasoning section?",
      options: ["200–800", "300–700", "130–170", "400–600"],
      correctAnswer: "0–60",
    },
    {
      id: 111,
      test: "gmat",
      question: "How much time is allotted for the GMAT Integrated Reasoning section?",
      options: ["30 minutes", "40 minutes", "45 minutes", "60 minutes"],
      correctAnswer: "30 minutes",
    },
    {
      id: 112,
      test: "gmat",
      question: "Which of the following is NOT a topic in the GMAT Integrated Reasoning section?",
      options: ["Multi-Source Reasoning", "Table Analysis", "Reading Comprehension", "Graphics Interpretation"],
      correctAnswer: "Reading Comprehension",
    },
    {
      id: 113,
      test: "gmat",
      question: "What is the time limit for the GMAT Quantitative Reasoning section?",
      options: ["30 minutes", "35 minutes", "40 minutes", "45 minutes"],
      correctAnswer: "62 minutes",
    },
    {
      id: 114,
      test: "gmat",
      question: "What is the time limit for the GMAT Verbal Reasoning section?",
      options: ["35 minutes", "40 minutes", "45 minutes", "60 minutes"],
      correctAnswer: "65 minutes",
    },
    {
      id: 115,
      test: "gmat",
      question: "How many questions are there in the GMAT Integrated Reasoning section?",
      options: ["10", "12", "15", "20"],
      correctAnswer: "12",
    },
    {
      id: 116,
      test: "gmat",
      question: "What kind of questions are included in the GMAT Data Sufficiency section?",
      options: ["Multiple-choice", "Short answer", "True/False", "Essay writing"],
      correctAnswer: "Multiple-choice",
    },
    {
      id: 117,
      test: "gmat",
      question: "Which of the following is a key focus of the GMAT Verbal Reasoning section?",
      options: ["Critical Reasoning", "Math questions", "Science reasoning", "Analytical writing"],
      correctAnswer: "Critical Reasoning",
    },
    {
      id: 118,
      test: "gmat",
      question: "What is the format of the GMAT exam?",
      options: ["Online only", "Paper-based", "Computer Adaptive Test", "Multiple-choice"],
      correctAnswer: "Computer Adaptive Test",
    },
    {
      id: 119,
      test: "gmat",
      question: "How is the GMAT scored?",
      options: ["Linear scoring system", "Computer-based scoring", "Algorithm-based scoring", "Score adjusted per question difficulty"],
      correctAnswer: "Score adjusted per question difficulty",
    },
    {
      id: 120,
      test: "gmat",
      question: "Which of the following types of questions are found in the GMAT Verbal Reasoning section?",
      options: ["Sentence correction", "Reading comprehension", "Critical reasoning", "All of the above"],
      correctAnswer: "All of the above",
    },
  ];

export default testQuestions;